
import { TaskCategory, type MainMission, type StrangerMission, type Challenge, type Collectible, type Miscellaneous, type GameTask } from './types';

export const mainMissions: MainMission[] = [
  // Chapter 1
  {
    id: 'ms-1',
    chapter: 1,
    name: 'Outlaws from the West',
    description: 'After a failed ferry robbery, the gang are forced to flee into the mountains of Ambarino.',
    goldMedalObjectives: [
      'Take no damage during the shootout.',
      'Loot 6 or more items from Adler Ranch.',
      'Complete with at least 80% accuracy.',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-2',
    chapter: 1,
    name: 'Enter, Pursued by a Memory',
    description: 'Javier and Arthur go looking for John, who has been missing for a few days.',
    goldMedalObjectives: [
      'Kill all the wolves without taking any damage.',
      'Complete with at least 80% accuracy.',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-3',
    chapter: 1,
    name: 'Old Friends',
    description: 'The gang finds shelter from the blizzard and plans their next move.',
    goldMedalObjectives: [
      'Catch and hogtie Kieran within 45 seconds',
      'Kill 3 O\'Driscolls in the same Dead Eye use',
      'Complete within 15 minutes and 30 seconds',
      'Get 15 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-4',
    chapter: 1,
    name: 'The Aftermath of Genesis',
    description: 'Arthur and Charles go hunting for food.',
    goldMedalObjectives: [
      'Kill each deer with one arrow',
      'Do not spook either deer',
      'Get a clean kill on the second dear',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-5',
    chapter: 1,
    name: 'Who the Hell is Leviticus Cornwall?',
    description: 'The gang decides to rob a train belonging to the wealthy industrialist, Leviticus Cornwall.',
    goldMedalObjectives: [
      'Save Lenny when he is hanging on the train',
      'After stopping the train, take out the guards within 1 minute 30 seconds',
      'Take no damage during the shootout',
      'Get 10 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-6',
    chapter: 1,
    name: 'Eastward Bound',
    description: 'The gang leaves the mountains and heads for a new camp at Horseshoe Overlook.',
    goldMedalObjectives: ['Pick up Javier when entering Horseshoe Overlook', 'Complete within 6 minutes'],
    category: TaskCategory.MainStory,
  },
  // Chapter 2
  {
    id: 'ms-7',
    chapter: 2,
    name: 'Polite Society, Valentine Style',
    description: 'Uncle, Tilly, Karen, and Mary-Beth have gone into Valentine. Arthur goes to find them.',
    goldMedalObjectives: [
      'Return the lost wagon horse to its owner',
      'Find Karen within 45 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-8',
    chapter: 2,
    name: 'Americans at Rest',
    description: 'A bar fight breaks out in Valentine after Arthur, Javier, and Charles have a drink.',
    goldMedalObjectives: [
      'Save Javier within 15 seconds',
      'Defeat Tommy within 1 minute 30 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-9',
    chapter: 2,
    name: 'Exit Pursued by a Bruised Ego',
    description: 'Hosea takes Arthur to hunt a legendary bear.',
    goldMedalObjectives: [
      'Track the bear within 1 minute 30 seconds',
      'Shoot the bear at least 6 times',
      'Complete within 12 minutes',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-10',
    chapter: 2,
    name: 'Who is Not without Sin',
    description: 'Reverend Swanson gets into trouble in Flatneck Station.',
    goldMedalObjectives: [
      'Win 2 hands of Poker',
      'Return Reverend to camp within 2 minutes 5 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-11',
    chapter: 2,
    name: 'Money Lending and Other Sins I-III',
    description: 'Leopold Strauss sends Arthur to collect debts from several people.',
    goldMedalObjectives: ['Complete within 2 minutes 10 seconds'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-12',
    chapter: 2,
    name: 'Paying a Social Call',
    description: 'Kieran, a captured O\'Driscoll, leads Arthur to one of their hideouts.',
    goldMedalObjectives: [
      'Silently kill 4 O\'Driscolls',
      'Get 12 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-13',
    chapter: 2,
    name: 'A Quiet Time',
    description: 'Arthur and Lenny have a wild night out in Valentine.',
    goldMedalObjectives: [
      'Try to make amends with an old rival',
      'Catch Lenny in the act',
      'Don\'t get arrested',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-14',
    chapter: 2,
    name: 'Blessed are the Meek?',
    description: 'Arthur goes to rescue Micah from jail in Strawberry.',
    goldMedalObjectives: [
      'While escaping, kill all mounted Lawmen within 55 seconds',
      'Get 15 headshots',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-15',
    chapter: 2,
    name: 'The First Shall be Last',
    description: 'Arthur and Javier rescue Sean from bounty hunters.',
    goldMedalObjectives: [
      'Silently kill the bounty hunters by the river with Javier',
      'Shoot the rope to free Sean',
      'Get 10 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-16',
    chapter: 2,
    name: 'Pouring Forth Oil - I & II',
    description: 'John has a plan to rob a train.',
    goldMedalObjectives: [
      'Deliver the wagon to the drop off within 1 minute 45 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-17',
    chapter: 2,
    name: 'Pouring Forth Oil - III & IV',
    description: 'The gang attempts to rob Leviticus Cornwall\'s train.',
    goldMedalObjectives: [
      'Kill all the train guards before Sean fires a shot',
      'Clear the baggage car of loot',
      'Escape the Law within 1 minute 30 seconds',
      'Get 10 kills in Dead Eye',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-18',
    chapter: 2,
    name: 'A Fisher of Men',
    description: 'Arthur takes Jack fishing.',
    goldMedalObjectives: [
      'After arriving at the river, catch a fish within 1 minute 30 seconds',
      'Complete within 7 minutes 20 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-19',
    chapter: 2,
    name: 'The Spines of America',
    description: 'Hosea sends Arthur to steal a stagecoach.',
    goldMedalObjectives: [
      'Loot everything from Carmody Dell',
      'Don\'t get spotted',
      'Deliver the wagon to Emerald Ranch within 1 minute 10 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-20',
    chapter: 2,
    name: 'An American Pastoral Scene',
    description: 'Micah asks Arthur to help with a stagecoach robbery.',
    goldMedalObjectives: [
      'Headshot each of the mounted guards protecting the wagon',
      'Get 10 kills in Dead Eye',
      'Complete within 6 minutes',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-21',
    chapter: 2,
    name: 'The Sheep and the Goats',
    description: 'John and Arthur go to sell sheep in Valentine.',
    goldMedalObjectives: [
      'Herd all the sheep in to the pen in Valentine',
      'Get 25 headshots',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-22',
    chapter: 2,
    name: 'A Strange Kindness',
    description: 'Arthur helps a family in need.',
    goldMedalObjectives: [
      'Return the captive to his family within 1 minute 40 seconds',
      'Get 5 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  // Chapter 3
  {
    id: 'ms-23',
    chapter: 3,
    name: 'The New South',
    description: 'The gang moves to a new camp at Clemens Point.',
    goldMedalObjectives: [
      'Knock out Anders Anderson without taking a hit',
      'Catch and return Anders Anderson to jail within 5 minutes 30 seconds',
      'Catch a fish with Dutch and Hosea',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-24',
    chapter: 3,
    name: 'Further Questions of Female Suffrage',
    description: 'Arthur helps Pearson with a women\'s suffrage march.',
    goldMedalObjectives: [
      'Fend off the Lemoyne Raiders in less than 1 minute',
      'Get 5 headshots',
      'Complete with at least 85% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-25',
    chapter: 3,
    name: 'American Distillation',
    description: 'Dutch and Arthur raid a Braithwaite moonshine still.',
    goldMedalObjectives: [
      'Win the race back to camp',
      'Complete the mission without taking damage',
      'Get 10 headshots',
      'Complete with at least 70% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-26',
    chapter: 3,
    name: 'An Honest Mistake',
    description: 'A botched robbery leads to a shootout.',
    goldMedalObjectives: [
      'Save Uncle when he is overpowered',
      'Get 20 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-27',
    chapter: 3,
    name: 'Preaching Forgiveness as He Went',
    description: 'Arthur and Lenny investigate a group of gun runners.',
    goldMedalObjectives: [
      'Kill 10 Lemoyne Raiders with a long scoped rifle',
      'Complete within 11 minutes and 30 seconds',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-28',
    chapter: 3,
    name: 'Sodom? Back to Gomorrah',
    description: 'Bill, Karen, and Arthur rob the bank in Valentine.',
    goldMedalObjectives: [
      'Loot all the safes',
      'Headshot 5 mounted Lawmen during the horseback escape',
      'Get to Downes Ranch within 1 minute 55 seconds',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-29',
    chapter: 3,
    name: 'Advertising, the New American Art',
    description: 'Arthur helps Hosea sell some moonshine.',
    goldMedalObjectives: [
      'Headshot 5 Lemoyne Raiders in the saloon',
      'Complete with at least 90% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-30',
    chapter: 3,
    name: 'Horse Flesh for Dinner',
    description: 'Arthur helps John and Javier steal horses from the Braithwaites.',
    goldMedalObjectives: [
      'Kill the stable hand showing you the horses',
      'Catch the stallion within 10 seconds',
      'Get 5 headshots',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-31',
    chapter: 3,
    name: 'The Fine Joys of Tobacco',
    description: 'Arthur and Sean burn the Gray\'s tobacco fields.',
    goldMedalObjectives: [
      'Silently kill the Gray Sean distracts in the wagon store',
      'Douse the fields within 2 minutes 20 seconds',
      'Kill 5 grays during the escape',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-32',
    chapter: 3,
    name: 'Magicians for Sport',
    description: 'Arthur searches for Trelawny.',
    goldMedalObjectives: [
      'Inspect all the clues in Trelawny\'s Caravan',
      'While tracking, stay within 30 feet of Trelawny\'s trail',
      'Kill 2 bounty hunters in the cornfields within 1 minute',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-33',
    chapter: 3,
    name: 'Blessed are the Peacemakers',
    description: 'Micah, Dutch and Arthur attempt a parley with the O\'Driscolls.',
    goldMedalObjectives: [
      'Free yourself and perform self-surgery within 1 minute',
      'Recover your weapons from the O\'Driscoll\'s camp',
      'Kill the O\'Driscoll gang members that beat and shot you',
      'Escape the camp without being spotted',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-34',
    chapter: 3,
    name: 'A Short Walk in a Pretty Town',
    description: 'The Grays lead Bill, Sean, and Arthur into an ambush.',
    goldMedalObjectives: [
      'Kill 3 Lawmen in Dead Eye while saving Bill',
      'Complete using only sidearms',
      'Complete within 4 minutes 30 seconds',
      'Get 20 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-35',
    chapter: 3,
    name: 'Blood Feuds, Ancient and Modern',
    description: 'The gang attacks Braithwaite Manor to rescue Jack.',
    goldMedalObjectives: [
      'Headshot Gareth and Gerald Braithwaite',
      'Get 20 headshots',
      'Complete with at least 85% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-36',
    chapter: 3,
    name: 'The Battle of Shady Belle',
    description: 'The gang clears out Lemoyne Raiders from Shady Belle to make it their new camp.',
    goldMedalObjectives: [
      'Kill all the Lemoyne Raiders in Shady Belle',
      'Clear two bodies from Shady Belle within 1 minute 40 seconds',
      'Complete within 11 minutes',
    ],
    category: TaskCategory.MainStory,
  },
  // Chapter 4
  {
    id: 'ms-37',
    chapter: 4,
    name: 'The Joys of Civilization',
    description: 'The gang arrives in Saint Denis.',
    goldMedalObjectives: [
      'Catch the street urchin before he reaches the market',
      'Complete within 5 minutes 40 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-38',
    chapter: 4,
    name: 'Angelo Bronte, a Man of Honor',
    description: 'Dutch, Arthur, and John meet with Angelo Bronte to get Jack back.',
    goldMedalObjectives: [
      'Encounter the dog and the drunk',
      'Don\'t get spotted by the lawmen',
      'Escape the cemetery within 2 minutes 45 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-39',
    chapter: 4,
    name: 'No, No and Thrice, No',
    description: 'Miss Grimshaw and Tilly are in trouble with the Foreman Brothers.',
    goldMedalObjectives: [
      'Kill both of the Foreman boys yourself',
      'Get 5 headshots',
      'Complete with at least 85% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-40',
    chapter: 4,
    name: 'The Gilded Cage',
    description: 'Arthur attends a party at the mayor\'s house.',
    goldMedalObjectives: [
      'Pour a drink, compliment a guest\'s attire, accept a gift and save a life',
      'Follow the servant without being detected',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-41',
    chapter: 4,
    name: 'A Fine Night of Debauchery',
    description: 'Arthur helps Trelawny cheat at poker on a riverboat.',
    goldMedalObjectives: [
      'Win the game of Poker without Strauss\'s help',
      'After your cover is blown, escape the boat in under 35 seconds',
      'Get 5 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-42',
    chapter: 4,
    name: 'Horsemen, Apocalypses',
    description: 'The O\'Driscolls attack the camp.',
    goldMedalObjectives: [
      'Kill 5 O\'Driscolls with a headshot while on horseback',
      'Burn 3 O\'Driscoll wagons',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-43',
    chapter: 4,
    name: 'American Fathers',
    description: 'Arthur helps Eagle Flies deal with an oil company.',
    goldMedalObjectives: [
      'Infiltrate the factory by hiding in the wagon',
      'Reach Danbury\'s office without being detected',
      'Kill all the horseback pursuers during the escape',
      'Complete with at least 80% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-44',
    chapter: 4,
    name: 'Urban Pleasures',
    description: 'Lenny, Dutch and Arthur plan a trolley station robbery.',
    goldMedalObjectives: [
      'Rob all the customers on the trolley',
      'Kill 10 lawmen while on the trolley',
      'Prevent any lawmen from jumping on the back of the wagon',
      'Shoot the dynamite Lenny throws',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-45',
    chapter: 4,
    name: 'Country Pursuits',
    description: 'Dutch and Arthur go fishing with a local guide named Thomas.',
    goldMedalObjectives: [
      'Return Jules to the skiff within 1 minute 40 seconds',
      'Shoot the Bullgator 5 times',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-46',
    chapter: 4,
    name: 'Revenge is a Dish Best Eaten',
    description: 'The gang attacks Bronte\'s mansion.',
    goldMedalObjectives: [
      'Kill all of Bronte\'s men that are searching for you in the graveyard',
      'Loot the office for the money and the platinum pocket watch',
      'Get 20 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-47',
    chapter: 4,
    name: 'Banking, the Old American Art',
    description: 'The gang robs the bank in Saint Denis.',
    goldMedalObjectives: [
      'Crack the safes without making any mistakes',
      'Complete the mission using only sidearms',
      'Get 25 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  // Chapter 5
  {
    id: 'ms-48',
    chapter: 5,
    name: 'Welcome to the New World',
    description: 'Arthur washes up on the island of Guarma.',
    goldMedalObjectives: [
      'Take no damage from the soldiers',
      'Get 10 headshots',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-49',
    chapter: 5,
    name: 'A Kind and Benevolent Despot',
    description: 'Arthur and the gang help Hercule Fontaine fight against Fussar.',
    goldMedalObjectives: [
      'Get 10 headshots',
      'Get 5 headshots while in the same Dead Eye use',
      'Complete within 10 minutes 45 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-50',
    chapter: 5,
    name: 'Savagery Unleashed',
    description: 'Arthur frees some captive workers.',
    goldMedalObjectives: [
      'Escape with the captives in less than 2 minutes',
      'Get 10 headshots',
      'Complete with at least 80% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-51',
    chapter: 5,
    name: 'Hell Hath No Fury',
    description: 'The gang defends their position from Fussar\'s navy.',
    goldMedalObjectives: [
      'Prevent 4 boats from reaching the shore',
      'Destroy the Naval Ship without missing a shot',
      'Complete with at least 70% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-52',
    chapter: 5,
    name: 'Paradise Mercifully Departed',
    description: 'The gang leaves Guarma.',
    goldMedalObjectives: [
      'Kill the first 2 soldiers on the bridge with a headshot',
      'Kill 10 soldiers with a headshot while using the Gatling gun',
      'Complete with at least 85% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-53',
    chapter: 5,
    name: 'Dear Uncle Tacitus',
    description: 'Arthur returns to Shady Belle.',
    goldMedalObjectives: ['Complete within 8 minutes'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-54',
    chapter: 5,
    name: 'Fleeting Joy',
    description: 'The gang finds a new camp at Lakay.',
    goldMedalObjectives: [
      'Kill 2 Pinkertons during the Dead Eye ambush',
      'Get 5 headshots with the Gatling gun',
      'Get at least 70% accuracy with the Gatling gun',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-55',
    chapter: 5,
    name: 'A Fork in the Road',
    description: 'Arthur falls ill in Saint Denis.',
    goldMedalObjectives: ['Complete within 3 minutes 5 seconds'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-56',
    chapter: 5,
    name: 'That\'s Murfree Country',
    description: 'Arthur and Charles scout a new potential camp location.',
    goldMedalObjectives: [
      'Deliver Meredith to her mother within 2 minutes',
      'Get 15 headshots',
      'Complete with at least 85% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  // Chapter 6
  {
    id: 'ms-57',
    chapter: 6,
    name: 'Icarus and Friends',
    description: 'Arthur and Sadie plan to rescue John from prison.',
    goldMedalObjectives: [
      'Keep the balloon at the correct altitude for the entire journey',
      'Get 5 headshots from the balloon',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-58',
    chapter: 6,
    name: 'Visiting Hours',
    description: 'Arthur and Sadie rescue John from Sisika Penitentiary.',
    goldMedalObjectives: [
      'Get a headshot on each of the 3 prison guards on the tower',
      'Escape to the boat within 2 minutes 45 seconds',
      'Complete within 9 minutes',
      'Get 20 headshots',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-59',
    chapter: 6,
    name: 'Just a Social Call',
    description: 'Dutch and Arthur attack Leviticus Cornwall\'s forces in Annesburg.',
    goldMedalObjectives: [
      'Headshot 3 of Cornwall\'s men in Dead Eye',
      'Complete with at least 85% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-60',
    chapter: 6,
    name: 'A Rage Unleashed',
    description: 'Dutch and Arthur help the Wapiti Indians.',
    goldMedalObjectives: [
      'Knock out 2 soldiers on the boat',
      'Round up all the escaped horses and bring them to the shore',
      'Complete with at least 80% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-61',
    chapter: 6,
    name: 'The Delights of Van Horn',
    description: 'Arthur and Bill cause a distraction in Van Horn.',
    goldMedalObjectives: [
      'Get 5 headshots',
      'Complete with at least 85% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-62',
    chapter: 6,
    name: 'Archaeology for Beginners',
    description: 'Arthur helps Rains Fall recover a sacred artifact.',
    goldMedalObjectives: [
      'Recover the sacred artifact without being detected',
      'Recover the sacred artifact within 1 minute 30 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-63',
    chapter: 6,
    name: 'Honor, Amongst Thieves',
    description: 'Arthur helps Captain Monroe with a vaccination delivery.',
    goldMedalObjectives: [
      'Recover the vaccine without being detected',
      'Complete within 5 minutes',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-64',
    chapter: 6,
    name: 'The Bridge to Nowhere',
    description: 'Arthur helps plant dynamite on a bridge.',
    goldMedalObjectives: [
      'Plant the dynamite within 1 minute 35 seconds',
      'Escape the oncoming train within 19 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-65',
    chapter: 6,
    name: 'My Last Boy',
    description: 'Dutch rides to battle with the Wapiti against the army.',
    goldMedalObjectives: [
      'Save Paytah',
      'Get 30 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-66',
    chapter: 6,
    name: 'Our Best Selves',
    description: 'The gang robs a U.S. Army train carrying payroll and supplies.',
    goldMedalObjectives: [
      'Get a headshot in Dead Eye after jumping from Dutch\'s horse',
      'Get at least 80% accuracy while fighting on the train',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-67',
    chapter: 6,
    name: 'Red Dead Redemption',
    description: 'The gang fractures and Arthur must decide who to side with.',
    goldMedalObjectives: [
      'Get 7 headshots while covering Sadie from the lighthouse',
      'After leaving the island, reach the gang in 2 minutes',
      'Complete with at least 70% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  // Epilogue - Part 1
  {
    id: 'ms-68',
    chapter: 7,
    name: 'The Wheel',
    description: 'John Marston starts a new life at Pronghorn Ranch.',
    goldMedalObjectives: ['Complete within 10 minutes'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-69',
    chapter: 7,
    name: 'Simple Pleasures',
    description: 'John spends time with his family.',
    goldMedalObjectives: [
      'When milking the cow, fill the bucket within 10 seconds',
      'Complete within 4 minutes 30 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-70',
    chapter: 7,
    name: 'Farming, for Beginners',
    description: 'John learns to build a fence.',
    goldMedalObjectives: [
      'Fix the first section of fence in 1 minute 30 seconds',
      'Avoid being hit by the bull',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-71',
    chapter: 7,
    name: 'Fatherhood, for Beginners',
    description: 'John takes Jack riding.',
    goldMedalObjectives: [
      'Teach Jack to ride without his horse bucking him off',
      'Win the race back to Pronghorn Ranch',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-72',
    chapter: 7,
    name: 'Old Habits',
    description: 'John helps Mr. Dickens with some rustlers.',
    goldMedalObjectives: [
      'Defeat the Laramie without taking a hit',
      'Defeat the Laramie within 25 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-73',
    chapter: 7,
    name: 'Jim Milton Rides, Again?',
    description: 'John protects the ranch from Laramie rustlers.',
    goldMedalObjectives: [
      'Get 10 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-74',
    chapter: 7,
    name: 'Fatherhood, for Idiots',
    description: 'John builds a pre-cut house.',
    goldMedalObjectives: ['Build the house in 35 seconds'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-75',
    chapter: 7,
    name: 'Motherhood',
    description: 'The Marston family settles into their new home.',
    goldMedalObjectives: [
      'Get 5 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  // Epilogue - Part 2
  {
    id: 'ms-76',
    chapter: 8,
    name: 'Home of the Gentry?',
    description: 'John seeks work in Blackwater.',
    goldMedalObjectives: ['Complete within 2 minutes 30 seconds'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-77',
    chapter: 8,
    name: 'Gainful Employment',
    description: 'John looks for honest work.',
    goldMedalObjectives: [
      'After arriving in Strawberry, locate the bounty within 30 seconds',
      'After mounting your horse, catch and hogtie the bounty within 1 minute 15 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-78',
    chapter: 8,
    name: 'Bare Knuckle Friendships',
    description: 'John looks for Charles Smith in Saint Denis.',
    goldMedalObjectives: [
      'Find Charles in the fight club',
      'Don\'t let your health fall below 50%',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-79',
    chapter: 8,
    name: 'Home Improvement for Beginners',
    description: 'John, Uncle, and Charles build the ranch house.',
    goldMedalObjectives: ['Complete within 18 seconds'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-80',
    chapter: 8,
    name: 'An Honest Day\'s Labors',
    description: 'John and Sadie track down a bounty.',
    goldMedalObjectives: [
      'Kill all of Shane Finley\'s men in Dead Eye',
      'Catch and hogtie Shane Finley in less than 30 seconds',
      'Complete with at least 70% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-81',
    chapter: 8,
    name: 'The Tool Box',
    description: 'John and Charles retrieve some tools.',
    goldMedalObjectives: [
      'Headshot 5 of the Laramies in the house',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-82',
    chapter: 8,
    name: 'A New Jerusalem',
    description: 'The ranch is completed.',
    goldMedalObjectives: [
      'Hammer the nails in with 80% accuracy',
      'Complete within 3 minutes 35 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-83',
    chapter: 8,
    name: 'A Quick Favor for an Old Friend',
    description: 'Sadie needs help with some bounty hunters.',
    goldMedalObjectives: [
      'Force the bounty hunters to flee from the Adler ranch within 30 seconds',
      'Get 5 headshots',
      'Complete with at least 80% accuracy',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-84',
    chapter: 8,
    name: 'Uncle\'s Bad Day',
    description: 'Uncle is kidnapped.',
    goldMedalObjectives: [
      'Get 5 headshots',
      'Complete with at least 80% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-85',
    chapter: 8,
    name: 'Trying Again',
    description: 'John takes Abigail into town.',
    goldMedalObjectives: [
      'Catch a fish',
      'Complete within 5 minutes 20 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-86',
    chapter: 8,
    name: 'A Really Big Bastard',
    description: 'John and Sadie take on a big bounty.',
    goldMedalObjectives: [
      'Shoot the bear 4 times as it charges',
      'Headshot both the bounty hunters in Dead Eye',
      'Complete within 7 minutes 15 seconds',
    ],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-87',
    chapter: 8,
    name: 'A New Future, a New Life',
    description: 'John proposes to Abigail.',
    goldMedalObjectives: ['Complete within 7 minutes 30 seconds'],
    category: TaskCategory.MainStory,
  },
  {
    id: 'ms-88',
    chapter: 8,
    name: 'American Venom',
    description: 'John, Sadie, and Charles go after Micah.',
    goldMedalObjectives: [
      'Help Sadie catch the bounty hunter in less than 30 seconds',
      'Get 20 headshots',
      'Complete with at least 85% accuracy',
      'Complete the mission without taking any health items',
    ],
    category: TaskCategory.MainStory,
  },
];

export const strangerMissions: StrangerMission[] = [
  {
    id: 'sm-1',
    part: 1,
    name: 'A Test of Faith',
    description: 'Find all 30 Dinosaur Bones for the paleontologist, Deborah MacGuiness.',
    category: TaskCategory.Stranger,
  },
  {
    id: 'sm-2',
    part: 1,
    name: 'Smoking and other Hobbies',
    description: 'Collect a full set of 144 Cigarette Cards.',
    category: TaskCategory.Stranger,
  },
  {
    id: 'sm-3',
    name: 'A Fisher of Fish',
    part: 1,
    description: 'Catch 13 Legendary Fish for Jeremy Gill.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-4',
    name: 'Duchesses and other Animals',
    part: 1,
    description: 'Collect exotic items for Algernon Wasp.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-5',
    name: 'Geology for Beginners',
    part: 1,
    description: 'Find 10 Rock Carvings for Francis Sinclair.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-6',
    name: 'The Noblest of Men, and a Woman',
    part: 1,
    description: 'Interview gunslingers for a biographer.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-7',
    name: 'All That Glitters',
    part: 1,
    description: 'Find all treasure maps and their treasures.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-8',
    name: 'He\'s British, of Course',
    part: 1,
    description: 'Help a stranded circus performer find his missing animals.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-9',
    name: 'A Better World, A New Friend',
    part: 1,
    description: 'Help a scientist with his remote-controlled boat.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-10',
    name: 'The Artist\'s Way',
    part: 1,
    description: 'Help the artist Charles Châtenay.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-11',
    name: 'Arcadia for Amateurs',
    part: 1,
    description: 'Help the photographer Albert Mason.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-12',
    name: 'Oh, Brother',
    part: 1,
    description: 'Help two fighting brothers.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-13',
    name: 'The Iniquities of History',
    part: 1,
    description: 'Help an old man reclaim his stolen belongings.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-14',
    name: 'The Mercies of Knowledge',
    part: 1,
    description: 'Help Professor Andrew Bell III with his electric chair.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-15',
    name: 'A Bright Bouncing Boy',
    part: 1,
    description: 'Help the inventor Marko Dragic.',
    category: TaskCategory.Stranger
  },
  {
    id: 'sm-16',
    name: 'The Wisdom of the Elders',
    part: 1,
    description: 'Help a man clear a cursed native burial ground.',
    category: TaskCategory.Stranger
  },
];

export const challenges: Challenge[] = [
  { id: 'ch-b-1', challengeType: 'Bandit', rank: 1, description: 'Hold up 5 townsfolk.', category: TaskCategory.Challenge },
  { id: 'ch-b-2', challengeType: 'Bandit', rank: 2, description: 'Rob two coaches or return two stolen coaches to a Fence.', category: TaskCategory.Challenge },
  { id: 'ch-b-3', challengeType: 'Bandit', rank: 3, description: 'Rob the cash register in any four shops, in a single day.', category: TaskCategory.Challenge },
  { id: 'ch-b-4', challengeType: 'Bandit', rank: 4, description: 'Rob three coaches or return three stolen coaches to a Fence, in a single day.', category: TaskCategory.Challenge },
  { id: 'ch-b-5', challengeType: 'Bandit', rank: 5, description: 'Earn a $250 dollar bounty in one state.', category: TaskCategory.Challenge },
  { id: 'ch-b-6', challengeType: 'Bandit', rank: 6, description: 'Steal five horses, and sell them to the horse Fence at Clemens Cove.', category: TaskCategory.Challenge },
  { id: 'ch-b-7', challengeType: 'Bandit', rank: 7, description: 'Rob $50 of cash and valuables from townsfolk and travelers.', category: TaskCategory.Challenge },
  { id: 'ch-b-8', challengeType: 'Bandit', rank: 8, description: 'Steal seven wagons, and sell them to the Fence at Emerald Ranch.', category: TaskCategory.Challenge },
  { id: 'ch-b-9', challengeType: 'Bandit', rank: 9, description: 'Hogtie someone and leave them on the railway tracks, three times.', category: TaskCategory.Challenge },
  { id: 'ch-b-10', challengeType: 'Bandit', rank: 10, description: 'Complete five train robberies without dying or being caught.', category: TaskCategory.Challenge },
  { id: 'ch-e-1', challengeType: 'Explorer', rank: 1, description: 'Find a treasure map.', category: TaskCategory.Challenge },
  { id: 'ch-e-2', challengeType: 'Explorer', rank: 2, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-3', challengeType: 'Explorer', rank: 3, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-4', challengeType: 'Explorer', rank: 4, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-5', challengeType: 'Explorer', rank: 5, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-6', challengeType: 'Explorer', rank: 6, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-7', challengeType: 'Explorer', rank: 7, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-8', challengeType: 'Explorer', rank: 8, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-9', challengeType: 'Explorer', rank: 9, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-e-10', challengeType: 'Explorer', rank: 10, description: 'Find a treasure.', category: TaskCategory.Challenge },
  { id: 'ch-g-1', challengeType: 'Gambler', rank: 1, description: 'Win 5 hands of poker.', category: TaskCategory.Challenge },
  { id: 'ch-g-2', challengeType: 'Gambler', rank: 2, description: 'In blackjack, double down and win the hand five times.', category: TaskCategory.Challenge },
  { id: 'ch-g-3', challengeType: 'Gambler', rank: 3, description: 'Win three games of five finger fillet.', category: TaskCategory.Challenge },
  { id: 'ch-g-4', challengeType: 'Gambler', rank: 4, description: 'Bust one poker opponent out in each location (Flatneck Station, Saint Denis, Valentine).', category: TaskCategory.Challenge },
  { id: 'ch-g-5', challengeType: 'Gambler', rank: 5, description: 'Win three rounds of dominoes without drawing any tiles against two or fewer opponents.', category: TaskCategory.Challenge },
  { id: 'ch-g-6', challengeType: 'Gambler', rank: 6, description: 'Beat the blackjack dealer in two locations (Rhodes, Van Horn Trading Post).', category: TaskCategory.Challenge },
  { id: 'ch-g-7', challengeType: 'Gambler', rank: 7, description: 'Beat the five finger fillet opponent in each location (Strawberry, Valentine, Van Horn Trading Post).', category: TaskCategory.Challenge },
  { id: 'ch-g-8', challengeType: 'Gambler', rank: 8, description: 'Win three hands of blackjack, with three hits or more.', category: TaskCategory.Challenge },
  { id: 'ch-g-9', challengeType: 'Gambler', rank: 9, description: 'Win three games of dominoes in a row.', category: TaskCategory.Challenge },
  { id: 'ch-g-10', challengeType: 'Gambler', rank: 10, description: 'Win three hands of poker in a row.', category: TaskCategory.Challenge },
  { id: 'ch-h-1', challengeType: 'Herbalist', rank: 1, description: 'Pick 6 Yarrow.', category: TaskCategory.Challenge },
  { id: 'ch-h-2', challengeType: 'Herbalist', rank: 2, description: 'Pick and eat 4 species of berry.', category: TaskCategory.Challenge },
  { id: 'ch-h-3', challengeType: 'Herbalist', rank: 3, description: 'Craft seven items using sage as an ingredient.', category: TaskCategory.Challenge },
  { id: 'ch-h-4', challengeType: 'Herbalist', rank: 4, description: 'Pick five mushrooms, and feed them to your horse.', category: TaskCategory.Challenge },
  { id: 'ch-h-5', challengeType: 'Herbalist', rank: 5, description: 'Craft nine items using Indian tobacco as an ingredient.', category: TaskCategory.Challenge },
  { id: 'ch-h-6', challengeType: 'Herbalist', rank: 6, description: 'Pick fifteen different species of herb.', category: TaskCategory.Challenge },
  { id: 'ch-h-7', challengeType: 'Herbalist', rank: 7, description: 'Craft five special miracle tonics, and use them.', category: TaskCategory.Challenge },
  { id: 'ch-h-8', challengeType: 'Herbalist', rank: 8, description: 'Use oleander to craft six poison weapons.', category: TaskCategory.Challenge },
  { id: 'ch-h-9', challengeType: 'Herbalist', rank: 9, description: 'Pick one of each type of herb.', category: TaskCategory.Challenge },
  { id: 'ch-h-10', challengeType: 'Herbalist', rank: 10, description: 'Season and cook all eleven types of meat.', category: TaskCategory.Challenge },
  { id: 'ch-hh-1', challengeType: 'Horseman', rank: 1, description: 'Kill 5 rabbits from horseback.', category: TaskCategory.Challenge },
  { id: 'ch-hh-2', challengeType: 'Horseman', rank: 2, description: 'Jump over 3 obstacles in 15 seconds.', category: TaskCategory.Challenge },
  { id: 'ch-hh-3', challengeType: 'Horseman', rank: 3, description: 'Ride from Valentine to Rhodes in less than five minutes.', category: TaskCategory.Challenge },
  { id: 'ch-hh-4', challengeType: 'Horseman', rank: 4, description: 'While mounted, drag a person for 3300 feet using a lasso.', category: TaskCategory.Challenge },
  { id: 'ch-hh-5', challengeType: 'Horseman', rank: 5, description: 'Trample five animals while on horseback.', category: TaskCategory.Challenge },
  { id: 'ch-hh-6', challengeType: 'Horseman', rank: 6, description: 'Ride from Strawberry to Saint Denis in less than nine minutes, without touching water.', category: TaskCategory.Challenge },
  { id: 'ch-hh-7', challengeType: 'Horseman', rank: 7, description: 'Kill seven enemies from horseback, without dismounting.', category: TaskCategory.Challenge },
  { id: 'ch-hh-8', challengeType: 'Horseman', rank: 8, description: 'Kill nine predators from horseback.', category: TaskCategory.Challenge },
  { id: 'ch-hh-9', challengeType: 'Horseman', rank: 9, description: 'Ride from Van Horn Trading Post to Blackwater in less than seventeen minutes, without touching water.', category: TaskCategory.Challenge },
  { id: 'ch-hh-10', challengeType: 'Horseman', rank: 10, description: 'Break every breed of wild horse.', category: TaskCategory.Challenge },
  { id: 'ch-m-1', challengeType: 'Master Hunter', rank: 1, description: 'Skin 3 deer.', category: TaskCategory.Challenge },
  { id: 'ch-m-2', challengeType: 'Master Hunter', rank: 2, description: 'Get 3 perfect rabbit pelts.', category: TaskCategory.Challenge },
  { id: 'ch-m-3', challengeType: 'Master Hunter', rank: 3, description: 'Track ten different animal species using your binoculars.', category: TaskCategory.Challenge },
  { id: 'ch-m-4', challengeType: 'Master Hunter', rank: 4, description: 'Get a clean kill after calling an animal 5 times.', category: TaskCategory.Challenge },
  { id: 'ch-m-5', challengeType: 'Master Hunter', rank: 5, description: 'Skin three black or grizzly bears.', category: TaskCategory.Challenge },
  { id: 'ch-m-6', challengeType: 'Master Hunter', rank: 6, description: 'Kill five cougars with a bow, and skin them.', category: TaskCategory.Challenge },
  { id: 'ch-m-7', challengeType: 'Master Hunter', rank: 7, description: 'Use bait to lure and kill a herbivore, and a predator.', category: TaskCategory.Challenge },
  { id: 'ch-m-8', challengeType: 'Master Hunter', rank: 8, description: 'Catch three fish without using a fishing rod.', category: TaskCategory.Challenge },
  { id: 'ch-m-9', challengeType: 'Master Hunter', rank: 9, description: 'Catch an opossum playing opossum.', category: TaskCategory.Challenge },
  { id: 'ch-m-10', challengeType: 'Master Hunter', rank: 10, description: 'Kill the legendary panther "Giaguaro".', category: TaskCategory.Challenge },
  { id: 'ch-s-1', challengeType: 'Sharpshooter', rank: 1, description: 'Kill 3 flying birds.', category: TaskCategory.Challenge },
  { id: 'ch-s-2', challengeType: 'Sharpshooter', rank: 2, description: 'Kill 2 different species of animal in the same Dead Eye use.', category: TaskCategory.Challenge },
  { id: 'ch-s-3', challengeType: 'Sharpshooter', rank: 3, description: 'Kill 5 birds while on a moving train.', category: TaskCategory.Challenge },
  { id: 'ch-s-4', challengeType: 'Sharpshooter', rank: 4, description: 'Kill someone from at least 80 feet away with a tomahawk.', category: TaskCategory.Challenge },
  { id: 'ch-s-5', challengeType: 'Sharpshooter', rank: 5, description: 'Kill six animals without switching or reloading a weapon.', category: TaskCategory.Challenge },
  { id: 'ch-s-6', challengeType: 'Sharpshooter', rank: 6, description: 'Kill someone at least 660 feet (220 yards) away with a scoped rifle.', category: TaskCategory.Challenge },
  { id: 'ch-s-7', challengeType: 'Sharpshooter', rank: 7, description: 'Get seven headshots in a row.', category: TaskCategory.Challenge },
  { id: 'ch-s-8', challengeType: 'Sharpshooter', rank: 8, description: 'Disarm three opponents without switching or reloading a weapon.', category: TaskCategory.Challenge },
  { id: 'ch-s-9', challengeType: 'Sharpshooter', rank: 9, description: 'Shoot three hats off people in the same Dead Eye.', category: TaskCategory.Challenge },
  { id: 'ch-s-10', challengeType: 'Sharpshooter', rank: 10, description: 'Kill three flying birds with three consecutive scoped rifle shots.', category: TaskCategory.Challenge },
  { id: 'ch-su-1', challengeType: 'Survivalist', rank: 1, description: 'Catch 3 Bluegill fish.', category: TaskCategory.Challenge },
  { id: 'ch-su-2', challengeType: 'Survivalist', rank: 2, description: 'Hand 5 animals into camp or trapper.', category: TaskCategory.Challenge },
  { id: 'ch-su-3', challengeType: 'Survivalist', rank: 3, description: 'Kill 5 animals using a Varmint Rifle.', category: TaskCategory.Challenge },
  { id: 'ch-su-4', challengeType: 'Survivalist', rank: 4, description: 'Craft a dynamite arrow, fire arrow, improved arrow, poison arrow, and small game arrow.', category: TaskCategory.Challenge },
  { id: 'ch-su-5', challengeType: 'Survivalist', rank: 5, description: 'Catch a fish in the Bayou from a riverboat, and while standing on the train tracks.', category: TaskCategory.Challenge },
  { id: 'ch-su-6', challengeType: 'Survivalist', rank: 6, description: 'Kill an animal while it’s feeding on a corpse, five times.', category: TaskCategory.Challenge },
  { id: 'ch-su-7', challengeType: 'Survivalist', rank: 7, description: 'Kill eight small game animals with consecutive small game arrows.', category: TaskCategory.Challenge },
  { id: 'ch-su-8', challengeType: 'Survivalist', rank: 8, description: 'Craft a homing tomahawk, improved tomahawk, improved dynamite, and volatile fire bottle.', category: TaskCategory.Challenge },
  { id: 'ch-su-9', challengeType: 'Survivalist', rank: 9, description: 'Catch a fish that weighs at least 19lb.', category: TaskCategory.Challenge },
  { id: 'ch-su-10', challengeType: 'Survivalist', rank: 10, description: 'Catch one of every species of fish.', category: TaskCategory.Challenge },
  { id: 'ch-w-1', challengeType: 'Weapons Expert', rank: 1, description: 'Kill 3 enemies with a knife.', category: TaskCategory.Challenge },
  { id: 'ch-w-2', challengeType: 'Weapons Expert', rank: 2, description: 'Kill 3 enemies in 10 seconds using only throwing knives.', category: TaskCategory.Challenge },
  { id: 'ch-w-3', challengeType: 'Weapons Expert', rank: 3, description: 'Kill three birds of prey using tomahawks.', category: TaskCategory.Challenge },
  { id: 'ch-w-4', challengeType: 'Weapons Expert', rank: 4, description: 'Kill ten enemies with a shotgun, using crafted ammo.', category: TaskCategory.Challenge },
  { id: 'ch-w-5', challengeType: 'Weapons Expert', rank: 5, description: 'Kill five mounted enemies with one throwing knife per enemy.', category: TaskCategory.Challenge },
  { id: 'ch-w-6', challengeType: 'Weapons Expert', rank: 6, description: 'Kill four enemies with one stick of dynamite.', category: TaskCategory.Challenge },
  { id: 'ch-w-7', challengeType: 'Weapons Expert', rank: 7, description: 'Kill four enemies in a row with the same tomahawk.', category: TaskCategory.Challenge },
  { id: 'ch-w-8', challengeType: 'Weapons Expert', rank: 8, description: 'Kill fifteen enemies using a long-barreled sidearm.', category: TaskCategory.Challenge },
  { id: 'ch-w-9', challengeType: 'Weapons Expert', rank: 9, description: 'Kill nine unaware enemies from behind, using the bow.', category: TaskCategory.Challenge },
  { id: 'ch-w-10', challengeType: 'Weapons Expert', rank: 10, description: 'Kill a grizzly bear using only throwing knives, without taking damage.', category: TaskCategory.Challenge },
];

export const collectibles: Collectible[] = [
  { id: 'co-db-1', collectibleType: 'Dinosaur Bones', name: 'Heartlands Oil Field Bone', category: TaskCategory.Collectible },
  { id: 'co-cc-1', collectibleType: 'Cigarette Cards', name: 'Famous Gunslingers Card Set', category: TaskCategory.Collectible },
  { id: 'co-ex-1', collectibleType: 'Exotics', name: 'Lady of the Night Orchid', category: TaskCategory.Collectible },
  { id: 'co-rc-1', collectibleType: 'Rock Carvings', name: 'Mount Hagen Rock Carving', category: TaskCategory.Collectible },
  { id: 'co-ht-1', collectibleType: 'Hunting Requests', name: 'Rabbit and Squirrel', category: TaskCategory.Collectible },
  { id: 'co-ts-1', collectibleType: 'Treasure Maps', name: 'Jack Hall Gang Map', category: TaskCategory.Collectible },
  { id: 'co-df-1', collectibleType: 'Dreamcatchers', name: 'Elysian Pool Dreamcatcher', category: TaskCategory.Collectible },
];

export const miscellaneous: Miscellaneous[] = [
  { id: 'mi-1', name: 'Discover 5 Shacks', description: 'Find and enter 5 hidden shacks across the world.', category: TaskCategory.Miscellaneous },
  { id: 'mi-2', name: 'Kill 5 Legendary Animals', description: 'Hunt and skin 5 of the Legendary Animals.', category: TaskCategory.Miscellaneous },
  { id: 'mi-3', name: 'Play all 4 tabletop games', description: 'Play Poker, Blackjack, Dominoes, and Five Finger Fillet.', category: TaskCategory.Miscellaneous },
  { id: 'mi-4', name: 'Complete a Companion Activity', description: 'Go on an activity with a gang member at camp.', category: TaskCategory.Miscellaneous },
  { id: 'mi-5', name: 'Take a bath', description: 'Take a bath at a hotel.', category: TaskCategory.Miscellaneous },
  { id: 'mi-6', name: 'Watch a show', description: 'Watch a show at the theater in Saint Denis or Blackwater.', category: TaskCategory.Miscellaneous },
  { id: 'mi-7', name: 'Craft one of each item type', description: 'Craft a recipe in each of the six categories: cooking, tonics, horse care, ammo, hunting, and weapons.', category: TaskCategory.Miscellaneous },
];

export const allTasks: GameTask[] = [
  ...mainMissions,
  ...strangerMissions,
  ...challenges,
  ...collectibles,
  ...miscellaneous,
];

export const taskCategories = Object.values(TaskCategory);

    